### ISSUE TITLE
Allow CheckpointManager to best model only

### ISSUE THREAD

**Issue by mjurkus** [TensorSpeech/TensorFlowASR#103]
Currently, CheckpointManager saves all checkpoints. I would like to have an option to save only when the model improved. Basically same as [tf.keras.callbacks.ModelCheckpoint](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint)

**Comment by usimarit** [comment]
@mjurkus Updated to support training with keras built-in `fit`, which means it supports keras callbacks like ModelCheckpoint. Checkout the #118 for more detail :smile:

**Comment by mjurkus** [comment]
Yes, I saw the release :) Great news and thank you!
