### ISSUE TITLE
How to use custom vocabulary in conformer

### ISSUE THREAD

**Issue by ashishBT** [TensorSpeech/TensorFlowASR#104]
I want to use my custom vocabulary for transcription. I have found that there is an option in `config.yml` under `decoder_config:
  vocabulary: null` to achieve this. 
  I want to know the file format of vocabulary that I should use and how to use this vocabulary argument?

**Comment by usimarit** [comment]
Example vocabularies are in [vocabularies](https://github.com/TensorSpeech/TensorFlowASR/tree/main/vocabularies)
There're 3 types of supported vocabularies: Characters, Subwords and Sentencepiece. They can be found in [text_featurizer.py](https://github.com/TensorSpeech/TensorFlowASR/blob/main/tensorflow_asr/featurizers/text_featurizers.py).
Set `decoder_config: vocabulary: path_to_vocab_file` to use the generated vocabulary.

**Comment by ashishBT** [comment]
Thanks for your quick reply :)
