### ISSUE TITLE
import rnnt_loss issue

### ISSUE THREAD

**Issue by caohongnga** [TensorSpeech/TensorFlowASR#117]
Hi,
The "from warprnnt_tensorflow import rnnt_loss as warp_rnnt_loss" command raise an error:
...warprnnt_tensorflow/__init__.py", line 6, in <module>
    _warprnnt = tf.load_op_library(lib_file)
.../load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libwarprnnt.so: failed to map segment from shared object

How to fix the issue, please?
Thank you

**Comment by usimarit** [comment]
Did you run `./scripts/install_rnnt_loss.sh` with `CUDA_HOME` if you have cuda and without if you don't?

**Comment by caohongnga** [comment]
Thank you for you replying,
I already install ./scripts/install_rnnt_loss.sh and finish installing with:

warprnnt-tensorflow 0.1 is already the active version in easy-install.pth

Installed /home/nga/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg
Processing dependencies for warprnnt-tensorflow==0.1
Finished processing dependencies for warprnnt-tensorflow==0.1

**Comment by usimarit** [comment]
Could you provide the whole output after running `./scripts/install_rnnt_loss.sh`?

**Comment by caohongnga** [comment]
Full output of the command:
Cloning into 'warp-transducer'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 917 (delta 4), reused 12 (delta 3), pack-reused 894
Receiving objects: 100% (917/917), 253.00 KiB | 361.00 KiB/s, done.
Resolving deltas: 100% (465/465), done.
Checking connectivity... done.
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "8.0") 
-- cuda found TRUE
-- Building shared library with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/sda/Nga/TensorFlowASR/externals/warp-transducer/build
[  7%] Building NVCC (Device) object CMakeFiles/warprnnt.dir/src/warprnnt_generated_rnnt_entrypoint.cu.o
Scanning dependencies of target warprnnt
[ 14%] Linking CXX shared library libwarprnnt.so
[ 14%] Built target warprnnt
[ 21%] Building NVCC (Device) object CMakeFiles/test_time_gpu.dir/tests/test_time_gpu_generated_test_time.cu.o
Scanning dependencies of target test_time_gpu
[ 28%] Building CXX object CMakeFiles/test_time_gpu.dir/tests/random.cpp.o
g++: warning: /usr/bin/c++: linker input file unused because linking not done
make[2]: *** No rule to make target '/usr/local/cuda/lib64/libcurand.so.10', needed by 'test_time_gpu'.  Stop.
CMakeFiles/Makefile2:129: recipe for target 'CMakeFiles/test_time_gpu.dir/all' failed
make[1]: *** [CMakeFiles/test_time_gpu.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
2021-01-18 22:11:42.049411: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
CUDA_HOME not found in the environment so building without GPU support. To build with GPU support please define the CUDA_HOME environment variable. This should be a path which contains include/cuda.h
setup.py:63: UserWarning: Assuming tensorflow was compiled without C++11 ABI. It is generally true if you are using binary pip package. If you compiled tensorflow from source with gcc >= 5 and didn't set -D_GLIBCXX_USE_CXX11_ABI=0 during compilation, you need to set environment variable TF_CXX11_ABI=1 when compiling this bindings. Also be sure to touch some files in src to trigger recompilation. Also, you need to set (or unsed) this environment variable if getting undefined symbol: _ZN10tensorflow... errors
  warnings.warn("Assuming tensorflow was compiled without C++11 ABI. "
running install
running bdist_egg
running egg_info
creating warprnnt_tensorflow.egg-info
writing warprnnt_tensorflow.egg-info/PKG-INFO
writing dependency_links to warprnnt_tensorflow.egg-info/dependency_links.txt
writing top-level names to warprnnt_tensorflow.egg-info/top_level.txt
writing manifest file 'warprnnt_tensorflow.egg-info/SOURCES.txt'
reading manifest file 'warprnnt_tensorflow.egg-info/SOURCES.txt'
writing manifest file 'warprnnt_tensorflow.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/warprnnt_tensorflow
copying warprnnt_tensorflow/__init__.py -> build/lib.linux-x86_64-3.7/warprnnt_tensorflow
running build_ext
building 'warprnnt_tensorflow.kernels' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -B /home/nga/anaconda3/envs/tf-gpu/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/nga/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/tensorflow/include -I/home/nga/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/tensorflow -I/mnt/sda/Nga/TensorFlowASR/externals/warp-transducer/tensorflow_binding/../include -I/home/nga/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/tensorflow/include/external/nsync/public -I/home/nga/anaconda3/envs/tf-gpu/include/python3.7m -c src/warprnnt_op.cc -o build/temp.linux-x86_64-3.7/src/warprnnt_op.o -std=c++11 -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -Wno-return-type -I/home/nga/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
g++ -pthread -shared -B /home/nga/anaconda3/envs/tf-gpu/compiler_compat -L/home/nga/anaconda3/envs/tf-gpu/lib -Wl,-rpath=/home/nga/anaconda3/envs/tf-gpu/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/src/warprnnt_op.o -L../build -Wl,-R/mnt/sda/Nga/TensorFlowASR/externals/warp-transducer/build -lwarprnnt -o build/lib.linux-x86_64-3.7/warprnnt_tensorflow/kernels.cpython-37m-x86_64-linux-gnu.so -L/home/nga/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/tensorflow -l:libtensorflow_framework.so.2
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/warprnnt_tensorflow
copying build/lib.linux-x86_64-3.7/warprnnt_tensorflow/kernels.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/warprnnt_tensorflow
copying build/lib.linux-x86_64-3.7/warprnnt_tensorflow/__init__.py -> build/bdist.linux-x86_64/egg/warprnnt_tensorflow
byte-compiling build/bdist.linux-x86_64/egg/warprnnt_tensorflow/__init__.py to __init__.cpython-37.pyc
creating stub loader for warprnnt_tensorflow/kernels.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/warprnnt_tensorflow/kernels.py to kernels.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying warprnnt_tensorflow.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying warprnnt_tensorflow.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying warprnnt_tensorflow.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying warprnnt_tensorflow.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
warprnnt_tensorflow.__pycache__.__init__.cpython-37: module references __path__
warprnnt_tensorflow.__pycache__.kernels.cpython-37: module references __file__
creating dist
creating 'dist/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg
removing '/home/nga/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg' (and everything under it)
creating /home/nga/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg
Extracting warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg to /home/nga/anaconda3/envs/tf-gpu/lib/python3.7/site-packages
warprnnt-tensorflow 0.1 is already the active version in easy-install.pth

Installed /home/nga/anaconda3/envs/tf-gpu/lib/python3.7/site-packages/warprnnt_tensorflow-0.1-py3.7-linux-x86_64.egg
Processing dependencies for warprnnt-tensorflow==0.1
Finished processing dependencies for warprnnt-tensorflow==0.1

**Comment by usimarit** [comment]
The message says there's no `CUDA_HOME` env, try to delete the folder `externals/warp-transducer`, specify CUDA_HOME like in the instruction in `README.md` and rerun `scripts/install_rnnt_loss.sh`

**Comment by caohongnga** [comment]
Thank you very much.
Problem is sold. It is version conflict, missing libcurand.so.10
