### ISSUE TITLE
question about vocabulary 

### ISSUE THREAD

**Issue by lfgogogo** [TensorSpeech/TensorFlowASR#121]
Hi,i have some doubts about TensorFlowASR/vocabularies/english.characters,there seems to be 24 base characters only,what will happen if i put thousands of words in it?

**Comment by usimarit** [comment]
I define the file to store only **characters**, you can not treat them as *words* since it will convert **each character** to **its class** defined by the order of characters in the file.
If you want to use thousands of words, consider the **subwords** approach.
