### ISSUE TITLE
Negative RNNT loss  with TF 2.4 and CUDA 11.0

### ISSUE THREAD

**Issue by gandroz** [TensorSpeech/TensorFlowASR#129]
Am I the only person to have some negative losses with TF2.4 and CUDA11.0 ? I just upated TF from 2.3 to 2.4, recompile warprnnt and always got negative losses (even with the tests of the library). 
I tried the warprnnt library test (multibatch-gpu) with the RNNT loss implemented in TF and it seems good, so I'll try with this implementation. Maybe it could be the default one or maybe could we have a config on it ?

**Comment by pourfard** [comment]
I have the same issue. When I use TF2.4 or TF2.4.1 and CUDA 11.0 or CUDA 11.1 RNNT loss is negative and training is very slow.

I'm now trying TF2.3.0 and TF2.3.1 with CUDA 10.1 but i get another error:

```
Traceback (most recent call last):
  File "/home/mahdi/Temp/ASR/TensorFlowASR/examples/contextnet/train_contextnet.py", line 63, in <module>
    from tensorflow_asr.runners.transducer_runners import TransducerTrainer
  File "/home/mahdi/Temp/ASR/TensorFlowASR/tensorflow_asr/runners/transducer_runners.py", line 21, in <module>
    from ..losses.rnnt_losses import rnnt_loss
  File "/home/mahdi/Temp/ASR/TensorFlowASR/tensorflow_asr/losses/rnnt_losses.py", line 16, in <module>
    from warprnnt_tensorflow import rnnt_loss as warp_rnnt_loss
  File "/usr/local/lib/python3.6/dist-packages/warprnnt_tensorflow-0.1-py3.6-linux-x86_64.egg/warprnnt_tensorflow/__init__.py", line 6, in <module>
    _warprnnt = tf.load_op_library(lib_file)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/warprnnt_tensorflow-0.1-py3.6-linux-x86_64.egg/warprnnt_tensorflow/kernels.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
```

I'm really disappointed. Please somebody tell us which version of Tensorflow and CUDA are you using to run RNNT loss correctly.

**Comment by pourfard** [comment]
I installed python 3.8 (it was 3.6) and created a completely new virtual environment and installed Tensorflow 2.3.2 with CUDA 10.1 and changed line 26 in contextnet.py from `if activation in ["silu", "swish"]: return tf.nn.silu` to `if activation in ["silu", "swish"]: return tf.nn.swish` because `silu` is not defined in `tf.nn` and now RNNT loss is **positive** and **1s/batch** (it was 4s/batch).

**Comment by gandroz** [comment]
There is definitely an issue with CUDA11 (and maybe TF2.4) but I'm not an expert with CUDA and could not tell you :(
By the way, the RNNT loss implemented directly in TF works very well. Juste uninstall warprnnt and it should use the TF version. I verified that the results are the same (I just launched the same test as done with warprnnt and it gives me the same results)

**Comment by usimarit** [comment]
We should move to **rnnt loss in pure tf** (by not installing warp-transducer), since it was implemented based on warp-transducer, the warp-transducer depends greatly on CUDA and tensorflow versions and I don't work (not a maintainer) on errors from warp-transducer.
I'll update the instruction on README later :smile:

**Comment by gandroz** [comment]
I agree with you. I modified the warp-transducer tensorflow binding and CMakeList files and also some test files to be able to compile it with TF2.3. It worked great but it broke with TF2.4 and CUDA11.0. I don't know much about cuda programming so moving to the TF implementation is mandatory.

**Comment by tund** [comment]
TF 2.4 and CUDA 11 works fine for me. At the beginning, I got trouble with installing warp-transducer, but fixed it by removing compute_86 in CMakeLists.txt file, after cloning `git clone https://github.com/usimarit/warp-transducer.git`.
I use python 3.6 and install packages in Anaconda whenever possible. Here is my conda env file:
```
name: base
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.6.12
  - conda=4.9.2
  - pip=20.3.3
  - cudatoolkit=11.0.221
  - nvidia::cudnn=8.0.4
  - pytorch::pytorch=1.7.1
  - pytorch::torchvision=0.2.2
  - pytorch::torchaudio=0.7.2
  - jupyter=1.0.0
  - jupyterhub=1.0.0
  - pandas=1.1.5
  - matplotlib=3.3.2
  - pillow=8.1.0
  - scikit-learn=0.23.2
  - scikit-image=0.17.2
  - conda-forge::librosa=0.8.0
  - conda-forge::opencv=4.5.0
  - colorama=0.4.4
  - nltk=3.5
  - dill=0.3.3
  - shapely=1.7.1
  - cython=0.29.21
  - xmltodict=0.12.0
  - conda-forge::ghostscript=9.53.3
  - conda-forge::imagemagick=7.0.10_28
  - beautifulsoup4=4.9.3
  - conda-forge::pycocotools=2.0.2
  - future=0.18.2
  - python-json-logger=2.0.1
  - conda-forge::structlog=20.2.0
  - conda-forge::wand=0.6.5
  - conda-forge::ffmpeg-python=0.2.0
  - conda-forge::flake8=3.8.4
  - conda-forge::sentencepiece=0.1.92
  - conda-forge::sacremoses=0.0.43
  - conda-forge::fastbpe=0.1.0
  - pip:
    - tensorflow==2.4.0
    - tensorflow-datasets==4.2.0
    - gpustat==0.6.0
    - textdistance==4.2.0
    - exif==1.0.4
    - imagezmq==1.1.1
    - pywavefront==1.3.3
    - nlpaug==1.1.2
    - lmdb==1.0.0
    - symspellpy==6.7.0
    - face-recognition==1.3.0
    - pyroomacoustics==0.4.2
    - pypesq==1.2.4
    - tensorboard_plugin_profile==2.4.0
    - fairseq==0.10.2
    - seaborn==0.11.1
```

**Comment by gandroz** [comment]
@tund thanks for pointing me out to this repo, I got mine (which is relatively similar). The main difference was in the CMakeList.txt file where I declare arch for CUDA11. I missed the arch=sm_80 flag.... seems to be my mistake. However, I found in a doc that 

> If you only mention ‘-gencode‘, but omit the ‘-arch‘ flag, the GPU code generation will occur on the JIT compiler by the CUDA driver.

But there seems to be an issue with that.
