### ISSUE TITLE
Question: Conformer or Subword Conformer

### ISSUE THREAD

**Issue by mjurkus** [TensorSpeech/TensorFlowASR#134]
Could someone share some insights on which approach should I choose?
I can't find detailed information or comparison.

**Comment by usimarit** [comment]
@mjurkus You should use `Subword Conformer` (the approach in the paper) because Subwords is proved to give better performance than Characters.

**Comment by mjurkus** [comment]
What is the best approach then when having multiple datasets?

For example, I have 3 datasets.

2 generic datasets, that I would like to train my base model.
1 problem-specific dataset, that I would like to use for fine-tuning.

1. When training `base` model I would use subwords generated from "generic datasets" and when finetuning - only from "problem-specific"?
2. Can these subwords change in time? For example, new data became available?

**Comment by usimarit** [comment]
1. I think training the base model use the subwords generated from generic datasets, then combine them with subwords from the problem specific to train the later model
2. Subwords are estimated from dataset using statistics, so yes it could change in time and with what datasets you combine or use.
