### ISSUE TITLE
[Error with rnnt_loss while training subword_conformer] ValueError: Input tensor 'rnnt_loss/add_4:0' enters the loop with shape (1, None), but has shape (None, None) after one iteration

### ISSUE THREAD

**Issue by mukurgupta** [TensorSpeech/TensorFlowASR#144]
Hello
I am trying to train subword_conformer with rnnt loss in TF without installing warp-transducer as instructed in the readme but getting the following error. Any help would be appreciated.

Thanks
![issue0](https://user-images.githubusercontent.com/38879291/107831026-24dd7980-6db3-11eb-9986-fb6c66b69e2e.jpg)

![issue](https://user-images.githubusercontent.com/38879291/107830964-f6f83500-6db2-11eb-927f-3c83b9b4a865.jpg)

**Comment by usimarit** [comment]
The issue is reproduced. It happens for `batch_size=1`

**Comment by usimarit** [comment]
@mukurgupta Fixed in the [commit](https://github.com/TensorSpeech/TensorFlowASR/commit/dce43995548c9b0ba58ffa5c361e6aa9cfabf8b3)

**Comment by mukurgupta** [comment]
Yes, it's working fine now.
Thanks a lot, @usimarit for your prompt response and help.
