### ISSUE TITLE
Any example for colab or notebook

### ISSUE THREAD

**Issue by roboticsai** [TensorSpeech/TensorFlowASR#145]
Hello, isn't their any colab or notebook examples just like in TensorFlowTTS repo? Or file which shows how should i use this in my own module?

**Comment by usimarit** [comment]
I'll add some colab examples.
You can use this package like in some scripts in the [examples folder](https://github.com/TensorSpeech/TensorFlowASR/tree/main/examples) or make subclasses to modify the classes, functions for your purposes.

**Comment by usimarit** [comment]
Added in PR #177
