### ISSUE TITLE
OOM after a while

### ISSUE THREAD

**Issue by ulucsahin** [TensorSpeech/TensorFlowASR#147]
Hello, first of all, thank you for clear implementation.

I have an issue where I get OOM with the following error message:
`tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[2,1751,906,640]`

I tried different settings using both train_ga_subword_conformer.py and train_ga_conformer.py. 
- Created subwords with 4000 subword limit, batch size 2 and GA 4. With this setting, I get OOM error after step 32.
- Tried decreasing subwords to 1000. Same settings, I get OOM error after few hundred steps.
- Tried using character based training. Same settings, I get OOM after around 100 steps. If I increase batch size to 4, I get OOM after around 40-50 steps. With batch size 8, I get OOM after just a few steps.

I am training on P100. Initially nvidia-smi shows 15000 mb GPU memory usage (I guess TF just allocates beforehand) with GPU utilization changing between 20-80%. 

I use beam_width=5 as original config file.

What may be the reason for this issue? Thanks.

**Comment by usimarit** [comment]
I do notice this issue when training with GA.
But I have to make sure: Do you have this issue when training "without" GA?

**Comment by ulucsahin** [comment]
I tried running train_conformer.py and set accumulation_steps: 0. With batch_size 2, it trained 500 steps and started evaluation. So far it works without problems.

**Comment by ulucsahin** [comment]
Update: batch_size=2 caused same problem after around 30 minutes.

**Comment by usimarit** [comment]
@ulucsahin Can you try with smaller `joint_dim`, like 320, or even 144

**Comment by ulucsahin** [comment]
Sorry for the late reply.

I tried with joint_dim 144. batch_size=2, with no GA. I get the same error at step 18661/1531000. My longest audio is around 16 seconds. Maybe memory requirements explode on those files (still seems too high).

`[Train] [Epoch 1/20] |▏                   | 18661/1531000 [2:12:02<171:10:14,  2.45batch/s, transducer_loss=119.66762]2021-02-17 07:46:44.014171: W tensorflow/core/common_runtime/bfc_allocator.cc:433] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.06GiB (rounded to 2216899584)requested by op StatefulPartitionedCall/gradient_tape/conformer/conformer_joint/conformer_joint_vocab/Tensordot/MatMul/MatMul
Current allocation summary follows.`

**Comment by usimarit** [comment]
@ulucsahin Yeah, for librispeech which max duration is 10s, it took 11G for batch size 2, it not only depends on duration but also the length of the transcript (I see your output dim[2] is 1086 which is huge, mine is maximum 207 using vocabulary size 1030). So I think you should use subwords, with batch_size=1 and GA :smile: 
The conformer takes lots of memory due to self attention mechanism, which currently have no way to reduce the memory consumption, so we have to tweak the parameters

**Comment by ulucsahin** [comment]
I understand. So it is possibly running into long sentences during training and couldn't fit into memory, which makes sense. I will try to adjust configuration and my dataset so I can train.

Thank you for your help, I am closing the issue.
