### ISSUE TITLE
Error running training and testing examples ds2

### ISSUE THREAD

**Issue by roboticsai** [TensorSpeech/TensorFlowASR#148]
When trying to run the train_ds2.py i'm getting below error:
`NotFoundError: /home/ubuntu/mnt/Miscellanea/Datasets/Speech/LibriSpeech/train-clean-100/transcripts.tsv; No such file or directory`
From where should i download this dataset? 
Also it would be helpful for begineer on ASR to test the demos if their was a documentation or tutorial to run the examples.

**Comment by usimarit** [comment]
@roboticsai that's just an example, you have to download the dataset (LibriSpeech or any dataset that you want) and setup the `transcripts.tsv` files as in the [readme](https://github.com/TensorSpeech/TensorFlowASR/blob/main/tensorflow_asr/datasets/README.md)

**Comment by roboticsai** [comment]
Yes, i understood t hat. But i couldn't find the link from where i can download those dataset. Can you show me the link to the example dataset.

**Comment by roboticsai** [comment]
Ok, i think i got the model and dataset `https://modelzoo.co/model/deepspeech`. So i'll close this link.
