### ISSUE TITLE
Question: how to create .h5 weights file

### ISSUE THREAD

**Issue by lukaszsus** [TensorSpeech/TensorFlowASR#156]
Hello @usimarit,
I have trained ConformerNet. During the training some pairs of checkpoint files were created. Their names have following format:
```ckpt-{number}.index```
```ckpt-{number}.data-00000-of-00001```
But unfortunately, no .h5 weights files were created. Is there any possibility to create .h5 weights file based on that checkpoints?

Thanks in advance for your help. :-)

**Comment by usimarit** [comment]
@lukaszsus The checkpoint is defined in the example yaml `running_config`. You will see the .h5

**Comment by usimarit** [comment]
@lukaszsus And you can create a script to load the weights in tf format (your curreny checkpoints) and then save weights using .h5 format

**Comment by lukaszsus** [comment]
Thank you for your fast response.
I have defined checkpoint in my config.yml file in the same format as it is in example config:
```filepath: /(...)/checkpoints/{epoch:02d}.h5```
but no .h5 file was saved inside checkpoints directory during the training.
There is only `latest.h5` saved in running config outdir.

**Comment by usimarit** [comment]
@lukaszsus .h5 checkpoints only available in `train_keras_*` scripts

**Comment by lukaszsus** [comment]
Thank you for explanation.
