### ISSUE TITLE
suitable microphone to test automatic speech recognition

### ISSUE THREAD

**Issue by roboticsai** [TensorSpeech/TensorFlowASR#158]
Hello can you provide the information of which microphone did you used to test and validate this ASR package which gave the corresponding less word error rate? We are trying to use the speech recognition and conversational bot feature in owr robot.
How much important is the noise cancelation feature for the microphone being used to do the ASR task.

**Comment by usimarit** [comment]
@roboticsai the clearer the speech, the better the recognition. I didn't use any microphone to calculate wer, wer and cer are calculated from test dataset, if you want to know what microphone they used to create the dataset, please search for librispeech's description and may be you can find it ... or not if they didn't add to the description. The model I deployed on my website uses microphone from the browser, which depends on users' microphone on their machine.
