### ISSUE TITLE
checkpoint file can't created correctly

### ISSUE THREAD

**Issue by Sar-Dar** [TensorSpeech/TensorFlowASR#164]
Hello @usimarit,
I have trained Conformer with `train_keras_subword_conformer.py`, During the training some pairs of checkpoint files were created in states folder. When Training done, I can`t find any checkpoint file or .h5 file in any folder. checkpoints folder never  created. 
when I had training  with `train_subword_conformer.py`, never meet this kind of quession.
what I am do wrong, where is my trained model.

Thanks in advance for your help

**Comment by usimarit** [comment]
@Sar-Dar `train_subword_conformer.py` will create a `latest.h5` file in `outdir` like [this](https://github.com/TensorSpeech/TensorFlowASR/blob/283d1f2df3a4da021721c222a51c1e4bbc709238/tensorflow_asr/runners/transducer_runners.py#L46), `train_keras_subword_conformer.py` will store checkpoints to the place you define in [checkpoint](https://github.com/TensorSpeech/TensorFlowASR/blob/283d1f2df3a4da021721c222a51c1e4bbc709238/examples/conformer/config.yml#L119) in `config.yml`

**Comment by Sar-Dar** [comment]
I know, there is no such checkpoint file or folder where I defined in config.yml, so weird

**Comment by usimarit** [comment]
@Sar-Dar Did you create the folder `checkpoints`, if not, try to create it before training epoch ends?

**Comment by Sar-Dar** [comment]
no, I’m not. I’ll try

**Comment by Sar-Dar** [comment]
It works. thank you for your help. I also recommend fix into it
