### ISSUE TITLE
Infer based on tflite

### ISSUE THREAD

**Issue by iamweiweishi** [TensorSpeech/TensorFlowASR#166]
Hi,
I trained a ds2 model using LibriSpeech, and tried to convert the model to tflite referring to the 'tflite_conformer.py'. 
Then, I found that the converted tflite model's input is 'signal' with 'type=float32[1]', which means that the tflite model can only handle single input. In my view, something might be wrong with the converted model. 

Then, I trained and got a conformer tflite-model. And I tried to infer an audio by running 'examples/conformer/tflite_conformer.py'. But an Error occured:

Traceback (most recent call last):
  File "examples/demonstration/tflite_conformer.py", line 61, in <module>
    hyp = tflitemodel.get_tensor(output_details[0]["index"])
  File "/home/install/tensorflowASR-2.3/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 459, in get_tensor
    return self._interpreter.GetTensor(tensor_index)
ValueError: Invalid tensor size.

Tensorflow version: 2.3.0-gpu

BTW, is there any example that shows how to use ds2-tflite models?

Thank you.

**Comment by usimarit** [comment]
@iamweiweishi Could you run the `examples/demonstration/tflite_conformer.py` with the pretrained model I shared, to see if it runs in your case?

**Comment by iamweiweishi** [comment]
Yes, it works now. Thank you. @usimarit

**Comment by nyadla-sys** [comment]
@iamweiweishi have you converted conformer float32 tflite model to int8 tflite model(both weights and actiavtions)?
if not do you have any python script which does above step?

**Comment by Aegon007** [comment]
您好，您的邮件我已收到。我会尽快给您回复。祝好！
