### ISSUE TITLE
Call tflitemodel.invoke() makes program crash 

### ISSUE THREAD

**Issue by zhangguanqun** [TensorSpeech/TensorFlowASR#167]
I am working on tf lite version of Conformer, but not succeed yet.
When I run tests/conformer/test_conformer.py, program crashed in line "tflitemodel.invoke()".
`tflitemodel.set_tensor(
        input_details[2]["index"],
        tf.zeros(
            [config.model_config["prediction_num_rnns"], 2, 1, config.model_config["prediction_rnn_units"]],
            dtype=tf.float32
        )
    )`
`tflitemodel.invoke()`
`hyp = tflitemodel.get_tensor(output_details[0]["index"])`
Crash Msg is: Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

Environment:
tensorflow 2.3.2
TensorFlowASR latest

**Comment by usimarit** [comment]
@zhangguanqun Could you show me the full commandline when you run the script and the full error messages?

**Comment by zhangguanqun** [comment]
> @zhangguanqun Could you show me the full commandline when you run the script and the full error messages?

Just run: python tests/conformer/test_conformer.py
And got this:
INFO: Created TensorFlow Lite delegate for select TF ops.
INFO: TfLiteFlexDelegate delegate: 212 nodes delegated out of 2731 nodes with 130 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 26 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 1 nodes delegated out of 35 nodes with 1 partitions.


Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by zhangguanqun** [comment]
By the way, tflite model was converted successful.

**Comment by zhangguanqun** [comment]
FULL STACK:
/home/zhangguanqun/venv_tf_2.3.1/bin/python /home/zhangguanqun/projects/TensorFlowASR/tests/conformer/test_conformer.py
Model: "conformer_encoder"
______________________________________________________________________________________________________________________________________________________
Layer (type)                                                       Output Shape                                                Param #                
======================================================================================================================================================
conformer_encoder_subsampling (Conv2dSubsampling)                  (None, None, 2880)                                          188208                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_pe (PositionalEncodingConcat)                    (1, None, 144)                                              0                      
______________________________________________________________________________________________________________________________________________________
conformer_encoder_linear (Dense)                                   (None, None, 144)                                           414864                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_dropout (Dropout)                                (None, None, 144)                                           0                      
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_0 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_1 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_2 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_3 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_4 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_5 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_6 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_7 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_8 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_9 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_10 (ConformerBlock)                        (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_11 (ConformerBlock)                        (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_12 (ConformerBlock)                        (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_13 (ConformerBlock)                        (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_14 (ConformerBlock)                        (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_15 (ConformerBlock)                        (None, None, 144)                                           506736                 
======================================================================================================================================================
Total params: 8,710,848
Trainable params: 8,706,240
Non-trainable params: 4,608
______________________________________________________________________________________________________________________________________________________
Model: "conformer_prediction"
______________________________________________________________________________________________________________________________________________________
Layer (type)                                                       Output Shape                                                Param #                
======================================================================================================================================================
conformer_prediction_embedding (Embedding)                         (None, None, 320)                                           2215040                
______________________________________________________________________________________________________________________________________________________
conformer_prediction_dropout (Dropout)                             (None, None, 320)                                           0                      
______________________________________________________________________________________________________________________________________________________
conformer_prediction_ln_0 (LayerNormalization)                     (None, None, 320)                                           640                    
______________________________________________________________________________________________________________________________________________________
conformer_prediction_lstm_0 (LSTM)                                 [(None, None, 320), (None, 320), (None, 320)]               820480                 
======================================================================================================================================================
Total params: 3,036,160
Trainable params: 3,036,160
Non-trainable params: 0
______________________________________________________________________________________________________________________________________________________
Model: "conformer_joint"
______________________________________________________________________________________________________________________________________________________
Layer (type)                                                       Output Shape                                                Param #                
======================================================================================================================================================
conformer_joint_enc (Dense)                                        (None, None, 320)                                           46400                  
______________________________________________________________________________________________________________________________________________________
conformer_joint_pred (Dense)                                       (None, None, 320)                                           102400                 
______________________________________________________________________________________________________________________________________________________
conformer_joint_vocab (Dense)                                      multiple                                                    2221962                
======================================================================================================================================================
Total params: 2,370,762
Trainable params: 2,370,762
Non-trainable params: 0
______________________________________________________________________________________________________________________________________________________
Model: "conformer"
______________________________________________________________________________________________________________________________________________________
Layer (type)                                                       Output Shape                                                Param #                
======================================================================================================================================================
conformer_encoder (ConformerEncoder)                               (None, None, 144)                                           8710848                
______________________________________________________________________________________________________________________________________________________
conformer_prediction (TransducerPrediction)                        (None, None, 320)                                           3036160                
______________________________________________________________________________________________________________________________________________________
conformer_joint (TransducerJoint)                                  (None, None, None, 6922)                                    2370762                
======================================================================================================================================================
Total params: 14,117,770
Trainable params: 14,113,162
Non-trainable params: 4,608
______________________________________________________________________________________________________________________________________________________
Converted successfully with no timestamp
Converted successfully with timestamp
INFO: Created TensorFlow Lite delegate for select TF ops.
INFO: TfLiteFlexDelegate delegate: 212 nodes delegated out of 2731 nodes with 130 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 26 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 1 nodes delegated out of 35 nodes with 1 partitions.


Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by usimarit** [comment]
@zhangguanqun the default works on my machine with tf 2.3.2, did you change anything? config, code?

**Comment by zhangguanqun** [comment]
Thanks reply @usimarit 
I just replace vocabulary with my own vocab file path in tests/saved_modes/config.yml, did not change anything beside that.
My environment is TF 2.3.2 as you suggested.
`tensorboard              2.4.1
tensorboard-plugin-wit   1.8.0
tensorflow               2.3.2
tensorflow-datasets      4.2.0
tensorflow-estimator     2.3.0
tensorflow-hub           0.11.0
tensorflow-io            0.16.0
tensorflow-metadata      0.29.0
tensorflow-text          2.3.0
tensorrt                 7.0.0.11`

**Comment by usimarit** [comment]
@zhangguanqun Can you undo your changes and rerun the script? To see if it works on your machine.

**Comment by zhangguanqun** [comment]
@usimarit Thanks reply so quickly.
I undo all my changes, but it still not work.
Log is here
```
/home/zhangguanqun/venv_tf_2.3.1/bin/python /home/zhangguanqun/projects/TensorFlowASR/tests/conformer/test_conformer.py
Model: "conformer_encoder"
______________________________________________________________________________________________________________________________________________________
Layer (type)                                                       Output Shape                                                Param #                
======================================================================================================================================================
conformer_encoder_subsampling (Conv2dSubsampling)                  (None, None, 2880)                                          188208                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_pe (PositionalEncodingConcat)                    (1, None, 144)                                              0                      
______________________________________________________________________________________________________________________________________________________
conformer_encoder_linear (Dense)                                   (None, None, 144)                                           414864                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_dropout (Dropout)                                (None, None, 144)                                           0                      
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_0 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_1 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_2 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_3 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_4 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_5 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_6 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_7 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_8 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_9 (ConformerBlock)                         (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_10 (ConformerBlock)                        (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_11 (ConformerBlock)                        (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_12 (ConformerBlock)                        (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_13 (ConformerBlock)                        (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_14 (ConformerBlock)                        (None, None, 144)                                           506736                 
______________________________________________________________________________________________________________________________________________________
conformer_encoder_block_15 (ConformerBlock)                        (None, None, 144)                                           506736                 
======================================================================================================================================================
Total params: 8,710,848
Trainable params: 8,706,240
Non-trainable params: 4,608
______________________________________________________________________________________________________________________________________________________
Model: "conformer_prediction"
______________________________________________________________________________________________________________________________________________________
Layer (type)                                                       Output Shape                                                Param #                
======================================================================================================================================================
conformer_prediction_embedding (Embedding)                         (None, None, 320)                                           9280                   
______________________________________________________________________________________________________________________________________________________
conformer_prediction_dropout (Dropout)                             (None, None, 320)                                           0                      
______________________________________________________________________________________________________________________________________________________
conformer_prediction_ln_0 (LayerNormalization)                     (None, None, 320)                                           640                    
______________________________________________________________________________________________________________________________________________________
conformer_prediction_lstm_0 (LSTM)                                 [(None, None, 320), (None, 320), (None, 320)]               820480                 
======================================================================================================================================================
Total params: 830,400
Trainable params: 830,400
Non-trainable params: 0
______________________________________________________________________________________________________________________________________________________
Model: "conformer_joint"
______________________________________________________________________________________________________________________________________________________
Layer (type)                                                       Output Shape                                                Param #                
======================================================================================================================================================
conformer_joint_enc (Dense)                                        (None, None, 320)                                           46400                  
______________________________________________________________________________________________________________________________________________________
conformer_joint_pred (Dense)                                       (None, None, 320)                                           102400                 
______________________________________________________________________________________________________________________________________________________
conformer_joint_vocab (Dense)                                      multiple                                                    9309                   
======================================================================================================================================================
Total params: 158,109
Trainable params: 158,109
Non-trainable params: 0
______________________________________________________________________________________________________________________________________________________
Model: "conformer"
______________________________________________________________________________________________________________________________________________________
Layer (type)                                                       Output Shape                                                Param #                
======================================================================================================================================================
conformer_encoder (ConformerEncoder)                               (None, None, 144)                                           8710848                
______________________________________________________________________________________________________________________________________________________
conformer_prediction (TransducerPrediction)                        (None, None, 320)                                           830400                 
______________________________________________________________________________________________________________________________________________________
conformer_joint (TransducerJoint)                                  (None, None, None, 29)                                      158109                 
======================================================================================================================================================
Total params: 9,699,357
Trainable params: 9,694,749
Non-trainable params: 4,608
______________________________________________________________________________________________________________________________________________________
Converted successfully with no timestamp
Converted successfully with timestamp
INFO: Created TensorFlow Lite delegate for select TF ops.
INFO: TfLiteFlexDelegate delegate: 212 nodes delegated out of 2731 nodes with 130 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 26 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 1 nodes delegated out of 35 nodes with 1 partitions.


Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by zhangguanqun** [comment]
My system environment:
OS: ubuntu 18.04
CUDA: 10.2
CUDNN: 7.6.5
NVIDIA-SMI: 440.64
GPU: GTX 1070
GCC: 7.5.0

**Comment by usimarit** [comment]
@zhangguanqun Can you try running with tf cpu (no tensorflow-gpu)?

**Comment by zhangguanqun** [comment]
@usimarit Run with CPU not working, got same crash errors as GPU.
```
    with tf.device('/cpu:0'):
        tflitemodel.invoke()
    hyp = tflitemodel.get_tensor(output_details[0]["index"])
```
```
    with tf.device('/cpu:0'):
        test_conformer()
```
Both crash as before ;(

**Comment by usimarit** [comment]
@zhangguanqun this is more like the problem from your machine, not tensorflow itself (since it works on my machine installed with anaconda, python 3.8).

**Comment by zhangguanqun** [comment]
@usimarit I agree with you ;) It is more likely an individual case.
My current python is 3.6.9, I will update to python 3.8 to see what will happen.
Thx.

**Comment by zhangguanqun** [comment]
@usimarit Unfortunately, I upgrade python version to 3.8.6 and run the above script on 3 different machines(ubuntu server and desktop), all of them crash with the same error :(
In python crash log from ubutun system, there is:
```
Title
    python3.8 crashed with SIGSEGV in tflite::FlexDelegate::CopyFromBufferHandle()

StacktraceTop
    tflite::FlexDelegate::CopyFromBufferHandle(TfLiteContext*, int, TfLiteTensor*)() from /home/zhangguanqun/venv_tf_2.3.2/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
```

What should I do?

**Comment by zhangguanqun** [comment]
@usimarit 
In the following simple program, if test function return tf.signal.rfft(x, [512]), program crash, if test function return tf.reshape(x, [10, -1]), it works fine.
```
import numpy as np
import tensorflow as tf


class Tester(tf.Module):
    def __init__(self):
        super(Tester, self).__init__()

    @tf.function(input_signature=[tf.TensorSpec(shape=[100], dtype=tf.float32)])
    def test(self, x):
        # return tf.reshape(x, [10, -1])
        return tf.signal.rfft(x, [512])


model = Tester()
concrete_func = model.test.get_concrete_function()
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
# converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir='saved_models/pb/model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite = converter.convert()

TFLITE_FILE_PATH = 'content/tester.tflite'
with open(TFLITE_FILE_PATH, 'wb') as f:
    f.write(tflite)

# Load the TFLite model and allocate tensors.
# interpreter = tf.lite.Interpreter(model_path="content/test_variable.tflite")
interpreter = tf.lite.Interpreter(model_content=tflite)
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
```
The saved tflite model which return tf.signal.rfft(x, [512]) is sharing with url:
https://drive.google.com/file/d/1LY3h4MHIwGGi63TyWsNta6vNKluIdi38/view?usp=sharing

Could you download this file and check if it works fine on your machine, thanks

**Comment by usimarit** [comment]
@zhangguanqun I just tested on my machine and it works without any problem

**Comment by zhangguanqun** [comment]
@usimarit Thanks, simple script above run failed on all my 4 machines(3 ubuntu desktop, 1 ubuntu server), but it works fine on colab, I really have no idea about how to deal with it 😂😂😂

**Comment by zhangguanqun** [comment]
@usimarit 
**Update**
After a weekend researching, I got some findings:

1. With TF 2.3.X, tests/conformer/test_conformer.py run failed on all my machines, it may relativate to PAD opertor, @abattery give me this answer: https://github.com/tensorflow/tensorflow/issues/48106#issuecomment-808969122
2. With TF 2.4.1, tests/conformer/test_conformer.py also run failed with error "InvalidArgumentError: Attempting to add a duplicate function with the name: __inference_standard_lstm_21488", maybe someone had met this error. If i remove LSTM layer from Pred Network, it works fine.
3. With TF-nightly (2.5.0-dev20210210), everything works fine :)

I am closing this issue, thanks
