### ISSUE TITLE
TensorflowASR on Jetson Nano

### ISSUE THREAD

**Issue by curiousjit** [TensorSpeech/TensorFlowASR#175]
I am trying to install Tensorflow ASR on NVIDIA Jetson Nano. However I am getting errors regarding Tensorflow-tools. Since Jetpack for Jetson Nano is ARM based, I installed Tensorflow as mentioned [here](https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html#install). Although I always get an error that tensorflow-ASR requires Tensorflow-tools >= 0.10. It suggests either to relax the version requirements or to change the requirements. I believe it has something to do with ARM based environment here. Any help here?

**Comment by usimarit** [comment]
@curiousjit I don’t have any jetson nano, so I won’t be able to help you here.

I’ll close the issue here.
Feel free to create issues if you have questions on training, testing, serving tensorflow-asr.
