### ISSUE TITLE
Reproducing Pre-trained Conformer Model 

### ISSUE THREAD

**Issue by AgaDob** [TensorSpeech/TensorFlowASR#183]
Hi, thank you for providing the pre-trained conformer model!  I wanted to re-train it locally from scratch but having some issues:

1) The `train_dataset_config` section is missing from the config in the google drive? Would it be possible to include it, or is it identical to the example config in `examples/conformer/config.yml`? 

2) Also, could you clarify which training script was used to train - is it `examples/conformer/train_ga_subword_conformer.py`?

 Thank you!

**Comment by usimarit** [comment]
@AgaDob you use the `examples/conformer/config.yml` as a baseline config file to make customization from. The training script used to train is `examples/conformer/train_subword_conformer.py` in the version 0.x but for version 1.x it will be `examples/conformer/train.py`

**Comment by AgaDob** [comment]
Great thank you, but would you be able to release more details regarding specifically the pre-trained model config on the google drive? E.g., what subset of librispeech was it trained on (train-clean-100 only?) and whether any augmentations were used? Thanks you very much!

**Comment by usimarit** [comment]
@AgaDob the config is updated with the newest version 😄
