### ISSUE TITLE
Bugs introduced with refactoring

### ISSUE THREAD

**Issue by andreselizondo-adestech** [TensorSpeech/TensorFlowASR#184]
List of bugs introduced after the refactoring PR.
As I find new bugs, I'll list them here with their corresponding explanation.

I believe this is more convenient than creating an issue for each.

- [x] Training with SentencePiece
- [x] Creating Subwords vocab

**Comment by andreselizondo-adestech** [comment]
Training with SentencePiece.
At line [tensorflow_asr/featurizers/text_featurizers.py#L342](https://github.com/TensorSpeech/TensorFlowASR/blob/main/tensorflow_asr/featurizers/text_featurizers.py#L342).
Seems like this function is nowhere to be found, but at the same time, the default value for `model` in that function is `None`. So when being called from [examples/conformer/train.py#L68](https://github.com/TensorSpeech/TensorFlowASR/blob/main/examples/conformer/train.py#L68), model is not specified and is therefore `None`.

**Comment by andreselizondo-adestech** [comment]
Things I noticed:
1. No more support for GradientAccumulation. (In my case, I need this to run acceptable batch sizes)
2. Args --tbs and --ebs are no longer used. [examples/conformer/train.py#L144](https://github.com/TensorSpeech/TensorFlowASR/blob/main/examples/conformer/train.py#L144)

@usimarit Can you comment on these, please?

**Comment by usimarit** [comment]
@andreselizondo-adestech Updated in main branch, GradientAccumulation is easy to implement in custom training loop and is harder in keras loop, and in new version I drop support for custom training loop. I'll find a way to add support GA in keras loop.
Using keras training loop requires model to be compile with `global_batch_size` so I merge --tbs and --ebs in to one as --bs

**Comment by usimarit** [comment]
> Also, found something else:
> When creating subwords in [scripts/generate_vocab_subwords.py#L5](https://github.com/TensorSpeech/TensorFlowASR/blob/main/scripts/generate_vocab_subwords.py#L5), `TFSubwordFeaturizer` is not defined in file [tensorflow_asr/featurizers/text_featurizers.py#L189](https://github.com/TensorSpeech/TensorFlowASR/blob/main/tensorflow_asr/featurizers/text_featurizers.py#L189).

updated

**Comment by usimarit** [comment]
> @usimarit I implemented --tbs and --ebs by passing them to `.fit()` as `batch_size` and `validation_batch_size`.
> This also requires the dataset to be created with this batch size.
> 
> ```
> global_batch_size = args.tbs or config.learning_config.running_config.batch_size
> global_batch_size *= strategy.num_replicas_in_sync
> 
> global_eval_batch_size = args.ebs or global_batch_size
> global_eval_batch_size *= strategy.num_replicas_in_sync
> 
> train_data_loader = train_dataset.create(global_batch_size)
> eval_data_loader = eval_dataset.create(global_eval_batch_size)
> ```
> 
> ```
> streaming_conformer.fit(
>     train_data_loader,
>     batch_size=global_batch_size,
>     epochs=config.learning_config.running_config.num_epochs,
>     steps_per_epoch=train_dataset.total_steps,
>     validation_data=eval_data_loader,
>     validation_batch_size=global_eval_batch_size,
>     validation_steps=eval_dataset.total_steps,
>     callbacks=callbacks,
> )
> ```
> 
> Maybe this is good enough?

`validation_batch_size` is ignored when using `tf.data.Dataset` and this script also support for TPUs (which is static shape training) so the batch size of train and eval datasets must be the same.

**Comment by andreselizondo-adestech** [comment]
Closing, as I can't seem to find any more bugs.
