### ISSUE TITLE
Different features extracted from NumpySpeechFeaturizer and TFSpeechFeaturizer

### ISSUE THREAD

**Issue by zhangguanqun** [TensorSpeech/TensorFlowASR#189]
@usimarit 
With latest code you commited 3 days ago, I got extremly different features of the same audio with NumpySpeechFeaturizer and TFSpeechFeaturizer.
```
signal, _ = librosa.load(audio, sr=16000)
tf_features = tf_speech_featurizer.tf_extract(signal)
np_features = np_speech_featurizer.extract(signal)
```
tf_features not same as np_features, bug?

**Comment by zhangguanqun** [comment]
By the way, speech_featurizers.py contains compile errors:
1. `np.variance` should be `np.var`
2. line 323 and followings, `per_feature` should `be per_frame`

**Comment by usimarit** [comment]
> By the way, speech_featurizers.py contains compile errors:
> 
> 1. `np.variance` should be `np.var`
> 2. line 323 and followings, `per_feature` should `be per_frame`

My bad, fixed on main branch
