### ISSUE TITLE
Question: GpuTracer has collected 0 callback api events and 0 activity events.

### ISSUE THREAD

**Issue by kkeevin123456** [TensorSpeech/TensorFlowASR#190]
When I run `python examples/deepspeech2/train.py --device 2` , it will stuck at the problem: GpuTracer has collected 0 callback api events and 0 activity events.
Please help me to address this problem.

Below is my terminal snapshot.
![image](https://user-images.githubusercontent.com/55287979/116242358-6b2e5c00-a798-11eb-9414-3db6974076c4.png)
![image](https://user-images.githubusercontent.com/55287979/116242463-8305e000-a798-11eb-80cc-0b4a715d5dd8.png)

Thanks.

**Comment by usimarit** [comment]
@kkeevin123456 Try changing the parameters of tensorboard callback in the config.yml

**Comment by kkeevin123456** [comment]
@usimarit Thank you very much. It's work right now, but why it doesn't use any GPU resource.

![image](https://user-images.githubusercontent.com/55287979/116502175-688d4d00-a8e5-11eb-82d8-0a8345c04976.png)

I don't know why it can't detect any GPU and it will take 35hr each epoch.
![image](https://user-images.githubusercontent.com/55287979/116502238-983c5500-a8e5-11eb-8ab2-60c412328baa.png)

Actually, the cuda is installed in that file.
![image](https://user-images.githubusercontent.com/55287979/116504363-af317600-a8ea-11eb-84ca-2b9f3c66b9ff.png)

Do you have some insight to address this problem?
Thanks.

**Comment by vaibhav016** [comment]
@kkeevin123456  Hey, i saw that libcudart libr is not loaded properly.  Can you fix this? Probablr problem is tensorflow and cuda version mismatch.  @usimarit Correct me if I am wrong.

**Comment by usimarit** [comment]
@vaibhav016 Sorry I don't have GPU to test this kind of problem, so you guys have to debug it yourself 😄 Anyway, just make sure you guys install all the drivers and packages for cuda and use tensorflow version that supports it 😄

**Comment by kkeevin123456** [comment]
@vaibhav016 Hi, I address this problem. The problem is tensorflow and cuda version mismatch! After I upgrade the version, the problem is fixed.

![image](https://user-images.githubusercontent.com/55287979/117011951-fb344e80-ad20-11eb-8438-67bcc618779f.png)

**Comment by kkeevin123456** [comment]
Hi all, when I run `python examples/deepspeech2/test.py --saved ./examples/deepspeech2/Model/states/ckpt-18` I got nothing but only print tensorVariable.

![image](https://user-images.githubusercontent.com/55287979/117565852-14a11600-b0e6-11eb-98bb-4a5861a4fd7d.png)

Here is my ckpt
![image](https://user-images.githubusercontent.com/55287979/117565859-21be0500-b0e6-11eb-9890-060ede84dbc8.png)

**Comment by vaibhav016** [comment]
@kkeevin123456  your model is saved in deepspeech2/checkpoints/{epoch:02d}.h5. Try this config path.

**Comment by kkeevin123456** [comment]
@vaibhav016 here is my config. Since there is nothing exist in /home/weidagogo/chi-shen/TensorFlowASR/examples/deepspeech2/Model/checkpoints/{epoch:02d}.h5, so I use the ckpt in Model/states

![image](https://user-images.githubusercontent.com/55287979/117594287-5eced980-b170-11eb-80fa-3f4e296a43ce.png)

**Comment by vaibhav016** [comment]
@kkeevin123456 Can you check the checkpoints folder? The model gets saved there.

**Comment by kkeevin123456** [comment]
@usimarit Thanks!! I try to fix this bug, but I can't 😄😄

**Comment by kkeevin123456** [comment]
@usimarit It seems like I don't install decoder? How to install this QQ
![image](https://user-images.githubusercontent.com/55287979/117834947-2c28fc00-b2aa-11eb-8fc1-851ac9ba686f.png)

**Comment by usimarit** [comment]
@kkeevin123456 Mine work fine, but note that currently tf.string doesn't support on GPU, so you'll have to use only CPU, did you use the flag --cpu?

**Comment by kkeevin123456** [comment]
@usimarit Yes, I try to use this flag --cpu, but it return the same problem.

**Comment by usimarit** [comment]
@kkeevin123456 try having a line `tf.config.set_visible_devices([], "GPU")` after `env_util.setup_devices([args.device], cpu=args.cpu)` in the `test.py`

**Comment by kkeevin123456** [comment]
@usimarit Thanks!! That can work!!! ORZ
