### ISSUE TITLE
Testing Fails on Jasper

### ISSUE THREAD

**Issue by kkiyani** [TensorSpeech/TensorFlowASR#197]
Facing this error while testing jasper.

![error](https://user-images.githubusercontent.com/67789395/118932111-175eff00-b961-11eb-96c6-ec752db13d2c.PNG)

env: 
![env](https://user-images.githubusercontent.com/67789395/118935167-aae5ff00-b964-11eb-97c7-ee7a1a2c5ba2.PNG)

**Comment by usimarit** [comment]
@kkiyani Please try the newest on branch main 😄

**Comment by kkiyani** [comment]
testing_jasper using subwords
facing this error
![new_error](https://user-images.githubusercontent.com/67789395/119453997-70f46e80-bd51-11eb-96d0-a8b4847518a7.PNG)

**Comment by usimarit** [comment]
I’ll close the issue here due to inactivity. Feel free to reopen if you have further questions.
