### ISSUE TITLE
'SubwordFeaturizer' object has no attribute 'vocab_array'

### ISSUE THREAD

**Issue by kkiyani** [TensorSpeech/TensorFlowASR#199]
testing Jasper using subwords

![new_error](https://user-images.githubusercontent.com/67789395/119471123-6f7f7200-bd62-11eb-81c6-aba2652ff2ac.PNG)

**Comment by usimarit** [comment]
@kkiyani I haven't tried Subword for CTC models but the PR should work

**Comment by kkiyani** [comment]
PR?

**Comment by kkiyani** [comment]
Thank you so much.

**Comment by kkiyani** [comment]
One more question: 
The snapshot for training session doesn't get save in the case on contextnet

**Comment by usimarit** [comment]
@kkiyani Could you be more specific?

**Comment by kkiyani** [comment]
It says it's not functional and sequential model, it's a subclass model. If you want to save the model use save_weight()

**Comment by usimarit** [comment]
> It says it's not functional and sequential model, it's a subclass model. If you want to save the model use save_weight() Or save_format='tf'

If you want to save the whole model in h5 format, then you'll have to define the `get_config` method of every layer and model classes, otherwise you'll have to go with the tf format.

**Comment by usimarit** [comment]
I’ll close the issue here. Feel free to reopen if you have further questions.
