### ISSUE TITLE
documnet reference for beam search used in transducer 

### ISSUE THREAD

**Issue by vivekyadav21** [TensorSpeech/TensorFlowASR#205]
@usimarit hi 
can you please give me the reference for your beam search used in transducer model

**Comment by usimarit** [comment]
@vivekyadav21 [Here](https://arxiv.org/pdf/1211.3711.pdf) you go 😄

**Comment by vivekyadav21** [comment]
@usimarit  thanku so much for your reply

**Comment by usimarit** [comment]
Feel free to reopen if you have further questions.
