### ISSUE TITLE
does anybody used the NumpySpeechFeautrizers ?

### ISSUE THREAD

**Issue by vivekyadav21** [TensorSpeech/TensorFlowASR#212]
@usimarit 
I tried with NumpySpeechFeautrizers but it neither give any error not showing any further progress

**Comment by usimarit** [comment]
@vivekyadav21 the NumpySpeechFeaturizer is getting deprecated, I'll remove it in near future and focus on pure tf implementation. If you want, you can customize it for it to work 😄

**Comment by vivekyadav21** [comment]
@usimarit thanks for your reply....btw somehow i managed to tackle my numpy task

**Comment by usimarit** [comment]
@vivekyadav21 I'll close the issue here, feel free to reopen if you have anything to ask.
