### ISSUE TITLE
Duration in transcripts.tsv

### ISSUE THREAD

**Issue by jun-danieloh** [TensorSpeech/TensorFlowASR#234]
I am just curious about whether it is normal to have `duration` in transcripts.tsv file. If it is usual, is it helpful that much? In which aspect?

**Comment by usimarit** [comment]
@jun-danieloh The `duration` is for precalculate the maximum length of signal for static shape training on TPUs (tpus require static shape where gpus are not - we can use dynamic shape on gpus).
