### ISSUE TITLE
Error in importing conformer

### ISSUE THREAD

**Issue by Ashbajawed** [TensorSpeech/TensorFlowASR#238]
Can any body help? I am getting no module errror 

ModuleNotFoundError: No module named 'tensorflow_asr.models.conformer
by command 
from tensorflow_asr.models.conformer import Conformer

I have installed 2.5.1 version of tensorflow_asr and have following configuration
tensorflow                   2.5.2
tensorflow-addons            0.14.0
tensorflow-datasets          4.4.0
tensorflow-estimator         2.5.0
tensorflow-gpu               2.6.0
tensorflow-hub               0.12.0
tensorflow-io                0.18.0
tensorflow-io-gcs-filesystem 0.18.0
tensorflow-metadata          1.2.0
tensorflow-text              2.5.0

**Comment by usimarit** [comment]
@Ashbajawed The `from tensorflow_asr.models.conformer import Conformer` has changed to `from tensorflow_asr.models.transducer.conformer import Conformer`. Please make sure you have the latest code on branch main

**Comment by usimarit** [comment]
Feel free to reopen if the problem still exists
