### ISSUE TITLE
Vietnamese dataset link failed

### ISSUE THREAD

**Issue by UESTCgan** [TensorSpeech/TensorFlowASR#249]
Hello, everyone
    I found this Vietnamese data set link is broken.   
     <html>
<body>

InfoRe Technology 2 (used in VLSP2019) | InfoRe2 (passwd: [BroughtToYouByInfoRe](https://files.huylenguyen.com/audiobooks.zip)) | 415h
-- | -- | --

</body>
</html>
    

 Does anybody have a new link? We look forward to your help!
    Thanks!

**Comment by usimarit** [comment]
@UESTCgan I fixed the link, could you try again?

**Comment by usimarit** [comment]
Feel free to reopen if the link is broken

**Comment by AlexBlack2202** [comment]
> Feel free to reopen if the link is broken

hi, can you fix the link, https://files.huylenguyen.com/audiobooks.zip, it return 504 error . 504 Gateway Time-out

**Comment by usimarit** [comment]
@AlexBlack2202 please recheck the link, sometimes my server gets disconnected from internet 😄

**Comment by chnk58hoang** [comment]
please check this dataset link. I think it failed again. Thank you very much !

**Comment by Aegon007** [comment]
您好，您的邮件我已收到。我会尽快给您回复。祝好！
