### ISSUE TITLE
how to debug tensor within pycharm

### ISSUE THREAD

**Issue by bihujrj** [TensorSpeech/TensorFlowASR#255]
can you help me ,i do not konw how to debug tensor within pycharm,  i can`t see the value within the tensor, it is difficult to debug tensorflow and your programe,thank you!

**Comment by usimarit** [comment]
@bihujrj Normally you put some breakpoints, have a script to run (like training or testing script), then run debug with that script, it will stop at the breakpoint and you'll see the tensor.
Sorry I rarely use debugging in pycharm, and also pycharm 😄 In my case, normally I run the script or pytest to test the modules or functions to see if they work as expected.

**Comment by usimarit** [comment]
I'll close the issue here. Feel free to reopen if you have further questions.
