### ISSUE TITLE
A question about Transducer when reading the code

### ISSUE THREAD

**Issue by guokr233** [TensorSpeech/TensorFlowASR#256]
Hello, I am reading the code of Transducer, I am not clear about TransducerJoint, in Transducer's call method, first use encoder to encode the input, and then use TransducerPrediction to predict, I don't understand why you use TransducerJoint at the end to combine the first two The output of the user encoded and prediction is transformed and added.
Thanks for your work.

**Comment by usimarit** [comment]
@guokr233 The `TransducerJoint` is this output distribution, the transcription network is the `Encoder` and the prediction network is the `TransducerPrediction`.
![Screenshot 2022-04-17 201900](https://user-images.githubusercontent.com/28498441/163716149-3759f3e5-0465-46d8-97a7-15c0b71223cb.png)
You can find more in this paper: [http://arxiv.org/abs/1211.3711](http://arxiv.org/abs/1211.3711)
