### ISSUE TITLE
How to get audio - word piece alignment for the conformer model

### ISSUE THREAD

**Issue by Turan111** [TensorSpeech/TensorFlowASR#258]
I have trained conformer model for the Librispeech config example. I would like to get audio - word piece alignment. to get output word pieces belongs to which parts of audio.

**Comment by usimarit** [comment]
@Turan111 you can check out the function `recognize_tflite_with_timestamp` in `base_transducer` file. This function returns transcript with its timestamp. So I think we can take the idea of this function to align the output classes with its input instead of the whole transcript.

**Comment by usimarit** [comment]
I'll close the issue here. Feel free to reopen if you have further questions.
