### ISSUE TITLE
continue training

### ISSUE THREAD

**Issue by wwyl2000** [TensorSpeech/TensorFlowASR#263]
Hi,

I started the training process and save some model in checkpoints. How can i use the most recent saved models and continue my training? If i start the training, will it load the most recent saved models or start from the very beginning?

**Comment by wwyl2000** [comment]
I found the solution. Thanks!

**Comment by EZMarouane** [comment]
can you @wwyl2000 help me on that i found the same probleme

**Comment by wwyl2000** [comment]
You need to pass in the model you want to start with with the parameter "pretrained" in train.py, then it will continue training from the pretrained model you set.

**Comment by usimarit** [comment]
@wwyl2000 The [https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/BackupAndRestore?hl=en](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/BackupAndRestore?hl=en) do this for us. You just need to specify the `states_dir` in the `config.yml` and just start the training, it will load the model, epoch info, optimizer from the `states_dir` and RESUME the training.

**Comment by wwyl2000** [comment]
@usimarit Cool, this method is much better, efficient. Thanks!

**Comment by usimarit** [comment]
I'll close the issue here. Feel free to reopen if you have further questions 😄
