### ISSUE TITLE
unexpected truncation of the dataset

### ISSUE THREAD

**Issue by wwyl2000** [TensorSpeech/TensorFlowASR#264]
Hi,

After one epoch, i got the following information:
W tensorflow/core/kernels/data/cache_dataset_ops.cc:768] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.

Did this cause any problem? How to resolve this issue?

Thanks for your help!

**Comment by usimarit** [comment]
Hi @wwyl2000, let me check if I can get rid of that warning.

**Comment by nglehuy** [comment]
No warning appears in the 2.x version, you can try again, feel free to reopen if the issue still persists
