### ISSUE TITLE
Unused dependency Pillow incompatible with python 3.6

### ISSUE THREAD

**Issue by cosminc98** [TensorSpeech/TensorFlowASR#273]
If I'm not wrong, the "Pillow" library was introduced [here](https://github.com/TensorSpeech/TensorFlowASR/commit/37ea12af04a8f2c13f75a617f4aa4331f95ce945#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R36) first and it's not used at all. In this case, it should be removed as it is [incompatible with python 3.6](https://pillow.readthedocs.io/en/stable/installation.html#python-support).

**Comment by usimarit** [comment]
#253 will fix this

**Comment by Aegon007** [comment]
您好，您的邮件我已收到。我会尽快给您回复。祝好！
