### ISSUE TITLE
Is the Vietnamese dataset INFoRe a single speaker dataset

### ISSUE THREAD

**Issue by tuntun990606** [TensorSpeech/TensorFlowASR#275]
Is the Vietnamese dataset INFoRe a single speaker dataset？There are many folders in the compressed package. I'm not sure if they are the words of one person

**Comment by usimarit** [comment]
@tuntun990606 the 25h dataset seems to be one person (I think), the others are multiple.

**Comment by usimarit** [comment]
I'm closing the issue here, feel free to reopen if you still have questions 😄
