### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by Akul2010** [TensorSpeech/TensorFlowASR#284]
Has this project been left or is this still being maintained?

**Comment by Aegon007** [comment]
您好，您的邮件我已收到。我会尽快给您回复。祝好！

**Comment by nglehuy** [comment]
It's still maintained, please watch the feat/wordpiece PR, thanks 🔥

**Comment by Aegon007** [comment]
您好，您的邮件我已收到。我会尽快给您回复。祝好！
