### ISSUE TITLE
How to convert .h5 to .tflite (TensorFlow Lite) model ?

### ISSUE THREAD

**Issue by bishowu** [TensorSpeech/TensorFlowASR#289]
Hi, I'm trying to convert **Pretrained Models** to .tflite model
![image](https://github.com/TensorSpeech/TensorFlowASR/assets/35730384/ab3d71a9-dbe1-456a-bccc-94be7adbc461)

So I put the .h5 model into my Google Drive and tried to convert it via Google Colab, here is the code

![image](https://github.com/TensorSpeech/TensorFlowASR/assets/35730384/0d3e4d11-d4f5-4c8a-b5ce-229975528c57)

Then I got  an error message as shown in the picture :
_ValueError: No model config found in the file at <tensorflow.python.platform.gfile.GFile object at 0x7a09526a3610>._

I don't know how to load the .h5 model correctly, could you give me a sample code ? Thank you.

**Comment by nglehuy** [comment]
The script to convert to tflite already [here](https://github.com/TensorSpeech/TensorFlowASR/blob/main/examples/tflite.py)

**Comment by nglehuy** [comment]
@bishowu I fixed the tflite conversion and add the inference example using tflite, please see [here](https://github.com/TensorSpeech/TensorFlowASR/blob/main/docs/tutorials/tflite.md)

I close this issue here, feel free to reopen if you have further questions.
