### ISSUE TITLE
ValueError: The channel dimension of the inputs should be defined. Found 'None'

### ISSUE THREAD

**Issue by huangzj421** [TensorSpeech/TensorFlowASR#37]
I tried to test with "python examples/conformer/train_conformer.py" when I encounted the above error. It happend in line 114:"conformer._build(speech_featurier.shape)" and the shape is [None,80,1], But in the last line of error, happened in "site-packages/tensorflow/python/keras/layers/convolutional.py:361 _get_input_channel" raise ValueError("The channel dimension of the inputs is None" I wondered what's wrong?

**Comment by usimarit** [comment]
> I tried to test with "python examples/conformer/train_conformer.py" when I encounted the above error. It happend in line 114:"conformer._build(speech_featurier.shape)" and the shape is [None,80,1], But in the last line of error, happened in "site-packages/tensorflow/python/keras/layers/convolutional.py:361 _get_input_channel" raise ValueError("The channel dimension of the inputs is None" I wondered what's wrong?

Can you give me the whole screenshot of the error?

**Comment by huangzj421** [comment]
> > I tried to test with "python examples/conformer/train_conformer.py" when I encounted the above error. It happend in line 114:"conformer._build(speech_featurier.shape)" and the shape is [None,80,1], But in the last line of error, happened in "site-packages/tensorflow/python/keras/layers/convolutional.py:361 _get_input_channel" raise ValueError("The channel dimension of the inputs is None" I wondered what's wrong?
> 
> Can you give me the whole screenshot of the error?

I am sorry for my mistake.

![1](https://user-images.githubusercontent.com/73161104/97536185-bf2dd300-19f7-11eb-91f3-31eb669d26b4.jpg)

**Comment by usimarit** [comment]
@huangzj421 Did you change anything? Because I've tested and I don't have that error.

**Comment by huangzj421** [comment]
> @huangzj421 Did you change anything? Because I've tested and I don't have that error.

No, I just followed your instruction to install TensorflowASR and noahchalifour/warp-transducer to install warprnnt_tensorflow. Both work well. And also I simply changed the dataset_config and running_config-outdir to my own path.
The main problem seems to happen in "speech_featurizer.shape". Is yours [None,80,1]?

**Comment by usimarit** [comment]
@huangzj421 try reinstalling the newest version of TensorFlowASR and tensorflow. And yes the shape is [None, 80, 1] excluding the batch dimension.

**Comment by huangzj421** [comment]
> @huangzj421 try reinstalling the newest version of TensorFlowASR and tensorflow. And yes the shape is [None, 80, 1] excluding the batch dimension.

I am sorry but I still get the same error.
I reviewed the "*/site-packages/tensorflow/python/keras/layers/convolutional.py" where the error exists and found in line 165: the data_format is channel-first. But the channel dim of your data shape is the last (1). I don't understand.

**Comment by usimarit** [comment]
> > @huangzj421 try reinstalling the newest version of TensorFlowASR and tensorflow. And yes the shape is [None, 80, 1] excluding the batch dimension.
> 
> I am sorry but I still get the same error.
> I reviewed the "*/site-packages/tensorflow/python/keras/layers/convolutional.py" where the error exists and found in line 165: the data_format is channel-first. But the channel dim of your data shape is the last (1). I don't understand.

The data_format in my repo is None, which is the default 'channels_last'.
Try redo the environment installation:
0. `conda create -n env python=3.7 tensorflow`.
1. `conda activate env`
2. `pip install -U tensorflow`
3. `python setup.py install`
4. `./scripts/install_rnnt_loss.sh`

**Comment by huangzj421** [comment]
> > > @huangzj421 try reinstalling the newest version of TensorFlowASR and tensorflow. And yes the shape is [None, 80, 1] excluding the batch dimension.
> > 
> > 
> > I am sorry but I still get the same error.
> > I reviewed the "*/site-packages/tensorflow/python/keras/layers/convolutional.py" where the error exists and found in line 165: the data_format is channel-first. But the channel dim of your data shape is the last (1). I don't understand.
> 
> The data_format in my repo is None, which is the default 'channels_last'.
> I've tested on some machine and it works well.
> Try redo the environment installation:
> 
> 1. `conda create -n env python=3.7 tensorflow`.
> 2. `conda activate env`
> 3. `pip install -U tensorflow`
> 4. `python setup.py install`
> 5. `./scripts/install_rnnt_loss.sh`

ok, thanks!
