### ISSUE TITLE
New Dataset Structure

### ISSUE THREAD

**Issue by masoudMZB** [TensorSpeech/TensorFlowASR#44]
I have created my own data as documentation said ( wave files and tsv file for them. near 300h  ) Now I can't understand what really should I do, to prepare it for training. is just the tsv and wav files enough to start training?

> To make a custom dataset, inherit the BaseDataset class and override following methods:
> 
> create to create tf.data.Dataset instance.
> parse for transforming tf.data.Dataset during creation by applyting tf.data.Dataset.map function.

I mean here. should I create a new py file and implement these 2 files? how is the implementation of these 2 functions? where this new py file should be imported?
an Example of this part may be really useful.

**Comment by usimarit** [comment]
The dataset I've created uses `tsv` files, if you only need to train and evaluate ASR, then `tsv` and `wav` files are enough.
If you want to create your own `tf.data.Dataset` for your own purpose, then you can inherit the `BaseDataset` class. The implementation you can find in the same directory of the `README.md` file where you read those documents.

**Comment by masoudMZB** [comment]
I got it. So I just change the directory of tsv file in .yml file in deep speech 2 examples folder and start training by running train_ds2.py

2 more question : 

1-) can I use a language model created by Kenlm repository as my language model? I mean should we use a special kind of language model or we can use any lm we want? and what if I don't have any? is there any default (because I'm in another language )?

2-) which part of the yml file refers to my previous checkpoints and reinitializing some layers? I want to transfer learning from your English pretrained model.

**Comment by usimarit** [comment]
1) For CTC model, the kenlm is supported, you can run `scripts/install_ctc_decoders.sh` to install baidu's ctc beam search and add the `Scorer` to text_featurizer. I'll update the example to make everything clearer.

2) For now I dont have pretrained deepspeech2, only conformer. But for transfer learning, you can load the pretrained weights before fitting model, no need for loading any checkpoints and that's not in yml. Yml file is only for storing general configurations like speech, model arch, dataset, augmentation, optimizer and training log dir.

**Comment by masoudMZB** [comment]
well, thanks for your guidance. you answered so clear.

So I'll close this issue. 

If I face any new problem, I'll reopen this.
Thanks

**Comment by tann9949** [comment]
@usimarit How do I add `scorer` to text_featurize? I have a kenlm language model loaded using the following command

```python
import kenlm

model = kenlm.Model(lm_path)
```

it seems like `text_featurizer.add_scorer(model)` or `text_featurizer.add_scorer(model.score)` isn't the right approach.
What is the right approach to add LM to the text featurizer?

Thanks in advance for any help

**Comment by usimarit** [comment]
@tann9949 Please checkout the simplfied baidu's ctc decoders [here](https://github.com/usimarit/ctc_decoders). It has the `scorer` for kenlm, this is the one that I use in ctc model [here](https://github.com/TensorSpeech/TensorFlowASR/blob/b42d6d49a2db0979b3865fb8ef13357a9e3e4c67/tensorflow_asr/models/ctc.py#L95).

**Comment by tann9949** [comment]
@usimarit I've tried adding `Scorer` from your example but encounter the error.

Here's my code
```python
from ctc_decoders import Scorer
import arpa

# load lm
alpha = 1.
beta = 1.
vocab = arpa.loadf(lm_path)[0].vocabulary()
scorer = Scorer(alpha=alpha, beta=beta, model_path=lm_path, vocabulary=vocab)

# load model
config = Config(config_path, learning=True)
speech_featurizer = TFSpeechFeaturizer(config.speech_config)
text_featurizer = CharFeaturizer(config.decoder_config)
text_featurizer.add_scorer(scorer)
conformer = Conformer(**config.model_config, vocabulary_size=text_featurizer.num_classes)
conformer._build(speech_featurizer.shape)
conformer.load_weights(model_path)
conformer.add_featurizers(speech_featurizer, text_featurizer)

signal = read_raw_audio(audio_path)
features = conformer.speech_featurizer.tf_extract(signal)
features = tf.expand_dims(features, 0)

hyp = conformer.recognize_beam(features, lm=True)[0].numpy()
```
and here's my error message
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-32-1d76b627d6f1> in <module>
      1 test_audio, ref = data[100]
      2 
----> 3 run_test(test_audio, ref)

<ipython-input-27-c80139016f06> in run_test(test_audio, ref)
     38     start_time = time.time()
     39 
---> 40     hyp = run_beam(test_audio, lm=True).replace('\x00', '')
     41     wer = get_wer(ref, hyp)
     42 

<ipython-input-5-2658a9c01ce0> in run_beam(audio_path, lm)
     12     features = tf.expand_dims(features, 0)
     13 
---> 14     hyp = conformer.recognize_beam(features, lm=lm)[0].numpy()
     15     return tf.compat.as_str_any(hyp)

~/.env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    778       else:
    779         compiler = "nonXla"
--> 780         result = self._call(*args, **kwds)
    781 
    782       new_tracing_count = self._get_tracing_count()

~/.env/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    812       # In this case we have not created variables on the first call. So we can
    813       # run the first trace but we should fail if variables are created.
--> 814       results = self._stateful_fn(*args, **kwds)
    815       if self._created_variables:
    816         raise ValueError("Creating variables on a non-first call to a function"

~/.env/lib/python3.8/site-packages/tensorflow/python/eager/function.py in __call__(self, *args, **kwargs)
   2827     with self._lock:
   2828       graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
-> 2829     return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
   2830 
   2831   @property

~/.env/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _filtered_call(self, args, kwargs, cancellation_manager)
   1841       `args` and `kwargs`.
   1842     """
-> 1843     return self._call_flat(
   1844         [t for t in nest.flatten((args, kwargs), expand_composites=True)
   1845          if isinstance(t, (ops.Tensor,

~/.env/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _call_flat(self, args, captured_inputs, cancellation_manager)
   1921         and executing_eagerly):
   1922       # No tape is watching; skip to running the function.
-> 1923       return self._build_call_outputs(self._inference_function.call(
   1924           ctx, args, cancellation_manager=cancellation_manager))
   1925     forward_backward = self._select_forward_and_backward_functions(

~/.env/lib/python3.8/site-packages/tensorflow/python/eager/function.py in call(self, ctx, args, cancellation_manager)
    543       with _InterpolateFunctionError(self):
    544         if cancellation_manager is None:
--> 545           outputs = execute.execute(
    546               str(self.signature.name),
    547               num_outputs=self._num_outputs,

~/.env/lib/python3.8/site-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     57   try:
     58     ctx.ensure_initialized()
---> 59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:

InvalidArgumentError:  TypeError: 'Scorer' object is not callable
Traceback (most recent call last):

  File "/Users/chompk/.env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 242, in __call__
    return func(device, token, args)

  File "/Users/chompk/.env/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 131, in __call__
    ret = self._func(*args)

  File "/Users/chompk/.env/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 302, in wrapper
    return func(*args, **kwargs)

  File "/Users/chompk/.env/lib/python3.8/site-packages/tensorflow_asr/models/transducer.py", line 512, in perform_beam_search
    lm_state, lm_score = self.text_featurizer.scorer(y_hat)

TypeError: 'Scorer' object is not callable


	 [[{{node while/body/_1/while/EagerPyFunc}}]] [Op:__inference_recognize_beam_2220757]

Function call stack:
recognize_beam
```

Thanks for any help in advance!

**Comment by usimarit** [comment]
@tann9949 I thought you were using CTC Models, the RNN Transducer models are not supported for LM yet, due to the beam search implementation is not completed.
