### ISSUE TITLE
Example of conformer

### ISSUE THREAD

**Issue by danielkope** [TensorSpeech/TensorFlowASR#45]
Would it be possible to provide an example of running inference on the unconverted (non-tflite) model as well. 

If I try to run the tflite if segfaults always. I think the conversation is a bit buggy.

my steps are:
In TensorFlowASR/examples/conformer:
1) train_conformer.py -> creates checkpoint and h5 file
2) tflite_conformer.py -> point to the h5 file
Then, I run TensorFlowASR/examples/demonstrations/conformer.py and point to tflite file produced.
INFO: TfLiteFlexDelegate delegate: 212 nodes delegated out of 2737 nodes with 130 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 26 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 0 nodes delegated out of 1 nodes with 0 partitions.

INFO: TfLiteFlexDelegate delegate: 1 nodes delegated out of 40 nodes with 1 partitions.

2020-11-16 23:01:41.748132: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
Segmentation fault (core dumped)

@Honghe @pquochuy @entn-at 
Thank you for the consideration!

**Comment by bill-kalog** [comment]
you can run the tf lite code if you use a cpu version of tf. For using gpu you need probably gpu delegate or something like that during extraction...
