### ISSUE TITLE
tflite conversation broken. 

### ISSUE THREAD

**Issue by danielkope** [TensorSpeech/TensorFlowASR#57]
HI -

With the latest pull, it seems the TFlite is broken.
(trying to convert a conformer model with GA training)

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Attempting to add a duplicate function with name: __inference_standard_lstm_20821 where the previous and current definitions differ. Previous definiton: signature {
  name: "__inference_standard_lstm_20821"
  input_arg {
    name: "inputs"
    type: DT_FLOAT
  }
  input_arg {
    name: "init_h"
    type: DT_FLOAT
  }
  input_arg {
    name: "init_c"
    type: DT_FLOAT
  }
  input_arg {
    name: "kernel"
    type: DT_FLOAT
  }
  input_arg {
    name: "recurrent_kernel"
    type: DT_FLOAT
  }

```

**Comment by tann9949** [comment]
Duplicate of #55 #41 , use `tf-nightly` version `2.4.0.dev20200901` to resolve the problem.

```bash
$ pip install tf-night==2.4.0.dev20200901
```

**Comment by danielkope** [comment]
Thanks - are you saying this is related to the tf.squeeze not being supported in tf-nightly, therefore the tf.reshape was used. And this is a tf-nightly version issue problem?

**Comment by danielkope** [comment]
2.4.0.dev20200901 is no longer available anymore but 2.4.0-dev20200902 works as well.

**Comment by usimarit** [comment]
The issue is reproduced (failed on newest stable 2.4.0). I'm working on this.

**Comment by usimarit** [comment]
@danielkope please confirm if the issue if resolved.

**Comment by usimarit** [comment]
I'll mark this resolved, if you guys still meet this error, just reopen the issue.
