### ISSUE TITLE
Creating Subword Vocabulary for Custom Language

### ISSUE THREAD

**Issue by m4ster-0f-pupp3t5** [TensorSpeech/TensorFlowASR#59]
Hi,

Thank you for your great work. How do I create the subword vocabulary for any custom language? Should I do it manually or alter the config file for auto-extraction and auto-generation of subwords?

**Comment by usimarit** [comment]
you can alter the config file and use the flag `--subwords_corpus` in any `train_subword_*.py` files to automatically generate subwords from corpus right before training.
