### ISSUE TITLE
Continue from last checkpoint

### ISSUE THREAD

**Issue by OmarHory** [TensorSpeech/TensorFlowASR#89]
Hello!
Can I continue from last checkpoint? I get OOM occasionally and I do not want to start all over again.

Thank you!

**Comment by OmarHory** [comment]
closing the issue. I added it myself.
1- Add this argument in the training script.

`parser.add_argument("--saved", type=str, default=None,
                    help="Path to saved model")`

2- Then after the `_build` method add the following lines:
```
if args.saved:
        conformer.load_weights(args.saved, by_name=True)
```

**Comment by usimarit** [comment]
@OmarHory This [line](https://github.com/TensorSpeech/TensorFlowASR/blob/cb084901d8995d8a0d726eb4c000bc902ee28026/tensorflow_asr/runners/base_runners.py#L311) loads the latest checkpoint
