### ISSUE TITLE
Increase buffer size when shuffling TF data

### ISSUE THREAD

**Issue by tund** [TensorSpeech/TensorFlowASR#96]
Hi @usimarit , we probably need to increase the shuffle buffer size to 1000 for example, in ASRDatasets here:
https://github.com/TensorSpeech/TensorFlowASR/blob/main/tensorflow_asr/datasets/asr_dataset.py#L108
https://github.com/TensorSpeech/TensorFlowASR/blob/main/tensorflow_asr/datasets/asr_dataset.py#L340
because `TFRECORD_SHARDS = 16` is too small.
This would help to feed better random data to the model (Reference: https://www.tensorflow.org/api_docs/python/tf/data/Dataset#shuffle)

**Comment by usimarit** [comment]
I'll make it an init parameter :smile:

**Comment by monatis** [comment]
Number of shards can also be configurable because shard file size may be huge based on the dataset with a fixed number of shards. Recommended shard file size is usually 100-200mb.
